Upgraded to scikit-image 0.14.2. This fixes 'ImportError: cannot import name _validate_lengths' in notebooks/simulation/experiment_generator_01.ipynb. See also https://github.com/scikit-image/scikit-image/issues/3551